<a href="https://colab.research.google.com/github/wilaipa/data_viz/blob/main/More_advanced_data_structure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Dictionary
สามารถ index ด้วยอะไรก็ได้ แต่ลำดับจะหายไป

In [1]:
ex_dict = { ' a ' :10, '1' :1, 'start' :5} #curly brackets ในการบอกว่าเป็น dict

In [2]:
ex_dict['start']

5

In [3]:
ex2_dict = {1: 'one', 2 : 'two', 3: 'three'}

In [4]:
ex2_dict[2]

'two'

# การเพิ่มสมาชิกใน dict

In [5]:
ex2_dict[0] = 'zero'

In [6]:
ex2_dict

{0: 'zero', 1: 'one', 2: 'two', 3: 'three'}

คำสั่งพิเศษที่ใช้บ่อย

In [7]:
ex2_dict.keys() # อยากรู้ว่าสมาชิกในนี้มีตัว index อะไรบ้าง

dict_keys([1, 2, 3, 0])

In [8]:
for index in ex2_dict.keys():
     print(index)

1
2
3
0


In [9]:
ex2_dict.values() # ให้ปริ้นค่าที่เป็นค่าของมัน

dict_values(['one', 'two', 'three', 'zero'])

dict เอาไปใช้ร่วมกับ dataframe ของ pandas

# Numpy array

numpy คือ package ที่ทำงานเกี่ยวกับ array ของตัวเลข (ที่มีคนเขียนขึ้นมาและนิยมใช้)

numpy -> number python

In [10]:
import numpy #วิธีเรียกใช้งาน package 


การสร้าง numpy array

In [11]:
ex_2d_array = numpy.array([[5.2,3.0,4.5],[9.1,0.1,0.3]])
print(ex_2d_array)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


การชี้ค่าใน numpy array

In [13]:
ex_2d_array[1,2] 

0.3

In [14]:
list_x = [[5.2,3.0,4.5] , [3.1,0.1,0.3]] #การชี้ list
print(len(list_x))

print(list_x[1])

print(list_x[1][2])


2
[3.1, 0.1, 0.3]
0.3


### operations

In [15]:
ex2_2d_array = numpy.array([[1,0,0],[0,0,1]])
print(ex2_2d_array)
print(ex_2d_array)

[[1 0 0]
 [0 0 1]]
[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


In [16]:
ex_2d_array.shape #ตรวจสอบขนาดของ matrix

(2, 3)

In [17]:
ex_2d_array + ex2_2d_array

array([[6.2, 3. , 4.5],
       [9.1, 0.1, 1.3]])

In [18]:
list_x = [[5.2,3.0,4.5],[9.1,0.1,0.3]]
list_x2 = [[1,0,0],[0,0,1]]

list_x + list_x2

[[5.2, 3.0, 4.5], [9.1, 0.1, 0.3], [1, 0, 0], [0, 0, 1]]

In [19]:
ex_2d_array - ex2_2d_array

array([[ 4.2,  3. ,  4.5],
       [ 9.1,  0.1, -0.7]])

In [23]:
ex_2d_array * ex2_2d_array #การคูณแบบ array เอาตำแหน่งเดียวกันมาคูณกัน

array([[5.2, 0. , 0. ],
       [0. , 0. , 0.3]])

matrix multiplication (dot product)

In [24]:
numpy.dot(ex_2d_array,ex2_2d_array) #มันคูณกันไม่ได้เพราะหลักแถวไม่เท่ากัน

ValueError: ignored

In [25]:
print(ex_2d_array)
print(ex_2d_array.T)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]
[[5.2 9.1]
 [3.  0.1]
 [4.5 0.3]]


In [26]:
numpy.dot(ex_2d_array,ex2_2d_array.T)

array([[5.2, 4.5],
       [9.1, 0.3]])

In [29]:
dot_mat = numpy.dot(ex_2d_array,ex2_2d_array.T)
print(dot_mat) 

[[5.2 4.5]
 [9.1 0.3]]


In [30]:
numpy.linalg.det(dot_mat)

-39.389999999999986

search google -> stackoverflow หรือ web ของ package สำหรับ operations อื่นๆ




## metrix slicing

In [31]:
print(ex_2d_array)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


In [32]:
ex_2d_array[1,1:] #ดู 0.1 กับ 0.3 ว่าอยู่แถวที่เท่าไหร่

array([0.1, 0.3])

In [33]:
ex_2d_array[:,:2]

array([[5.2, 3. ],
       [9.1, 0.1]])

HW 5 เขียน function คูณ matrix แล้ว test กับ matrix
- (2,3)*(3,2)
- (4,4)*(4,1)
- (2,2)*(2,2)

ห้ามใช้แบบดอท ให้ทำแบบคูณกัน